export default {
  id: 44,
  title: "TypeScript with Vue.js 3",
  slug: "typescript-with-vue-js-3",
  chapters: [
    {
      slug: "first-chapter",
      title: "Getting Started with TypeScript and Vue",
      duration: "15 min",
      course_order: 0,
      lessons: [
        {
          id: 735,
          title: "Introduction to TypeScript with Vue.js 3",
          slug: "introduction-to-typescript-with-vue-js-3",
          status: 1,
          watched: 0,
          free: 1,
          course_order: 1,
          duration: "5:33",
          scheduled_at: null,
          chapter_course_order: 0,
        },
        {
          id: 736,
          title: "Course PreRequisites and Dependencies",
          slug: "typescript-and-vue-js-3-course-prerequisites-and-dependencies",
          status: 1,
          watched: 0,
          free: 0,
          course_order: 2,
          duration: "2:33",
          scheduled_at: null,
          chapter_course_order: 0,
        },
        {
          id: 737,
          title: "Bootstrap a Vue.js and TypeScript Project",
          slug: "bootstrap-a-vue-js-and-typescript-project",
          status: 1,
          watched: 0,
          free: 0,
          course_order: 3,
          duration: "2:24",
          scheduled_at: null,
          chapter_course_order: 0,
        },
        {
          id: 738,
          title: "Setup VS Code for TypeScript and Vue",
          slug: "setup-vs-code-for-typescript-and-vue",
          status: 1,
          watched: 0,
          free: 0,
          course_order: 4,
          duration: "4:41",
          scheduled_at: null,
          chapter_course_order: 0,
        },
      ],
    },
    {
      slug: "second-chapter",
      title: "TypeScript and the Composition API",
      duration: "1 hr",
      course_order: 1,
      lessons: [
        {
          id: 739,
          title: "TypeScript in Vue Components",
          slug: "typescript-in-vue-components",
          status: 1,
          watched: 0,
          free: 1,
          course_order: 5,
          duration: "2:10",
          scheduled_at: null,
          chapter_course_order: 1,
        },
        {
          id: 740,
          title: "Typing Reactive Data",
          slug: "typing-reactive-data",
          status: 1,
          watched: 0,
          free: 0,
          course_order: 6,
          duration: "5:17",
          scheduled_at: null,
          chapter_course_order: 1,
        },
        {
          id: 741,
          title: "Typing Refs",
          slug: "typing-refs",
          status: 1,
          watched: 0,
          free: 0,
          course_order: 7,
          duration: "7:00",
          scheduled_at: null,
          chapter_course_order: 1,
        },
        {
          id: 742,
          title: "Typing Computed Props",
          slug: "typing-computed-props",
          status: 1,
          watched: 0,
          free: 0,
          course_order: 8,
          duration: "3:49",
          scheduled_at: null,
          chapter_course_order: 1,
        },
        {
          id: 743,
          title: "Typing Event Handlers",
          slug: "typing-event-handlers",
          status: 1,
          watched: 0,
          free: 0,
          course_order: 9,
          duration: "6:27",
          scheduled_at: null,
          chapter_course_order: 1,
        },
        {
          id: 744,
          title: "Declaring Component Events",
          slug: "declaring-component-events",
          status: 1,
          watched: 0,
          free: 0,
          course_order: 10,
          duration: "5:21",
          scheduled_at: null,
          chapter_course_order: 1,
        },
        {
          id: 745,
          title: "Typing Component Events",
          slug: "typing-component-events",
          status: 1,
          watched: 0,
          free: 1,
          course_order: 11,
          duration: "5:20",
          scheduled_at: null,
          chapter_course_order: 1,
        },
        {
          id: 746,
          title: "Refactoring in TypeScript",
          slug: "refactoring-in-typescript",
          status: 1,
          watched: 0,
          free: 0,
          course_order: 12,
          duration: "7:47",
          scheduled_at: null,
          chapter_course_order: 1,
        },
        {
          id: 755,
          title: "Challenge: Advance the App",
          slug: "challenge-advance-the-app",
          status: 1,
          watched: 0,
          free: 0,
          course_order: 13,
          duration: "7:48",
          scheduled_at: null,
          chapter_course_order: 1,
        },
        {
          id: 747,
          title: "Declaring and Typing Component Props",
          slug: "declaring-and-typing-component-props",
          status: 1,
          watched: 0,
          free: 1,
          course_order: 14,
          duration: "9:47",
          scheduled_at: null,
          chapter_course_order: 1,
        },
        {
          id: 748,
          title: "Typing Template Refs",
          slug: "typing-template-refs",
          status: 1,
          watched: 0,
          free: 0,
          course_order: 15,
          duration: "1:56",
          scheduled_at: null,
          chapter_course_order: 1,
        },
        {
          id: 749,
          title: "Typing Data Injected via Vue\u2019s Provide/Inject",
          slug: "typing-data-injected-via-vue-provide-inject",
          status: 1,
          watched: 0,
          free: 0,
          course_order: 16,
          duration: "8:32",
          scheduled_at: null,
          chapter_course_order: 1,
        },
      ],
    },
    {
      slug: "third-chapter",
      title: "TypeScript and the Options API",
      duration: "11 min",
      course_order: 2,
      lessons: [
        {
          id: 750,
          title: "Using TypeScript with the Options API in Components",
          slug: "using-typescript-with-the-options-api-in-components",
          status: 1,
          watched: 0,
          free: 1,
          course_order: 17,
          duration: "5:19",
          scheduled_at: null,
          chapter_course_order: 2,
        },
        {
          id: 751,
          title: "Augmenting Global Properties and Custom Options",
          slug: "augmenting-global-properties-and-custom-options",
          status: 1,
          watched: 0,
          free: 0,
          course_order: 18,
          duration: "4:46",
          scheduled_at: null,
          chapter_course_order: 2,
        },
        {
          id: 753,
          title: "Course Conclusion",
          slug: "typescript-with-vue-js-3-course-conclusion",
          status: 1,
          watched: 0,
          free: 0,
          course_order: 20,
          duration: "1:05",
          scheduled_at: null,
          chapter_course_order: 2,
        },
      ],
    },
  ],
};
